# fly.toml app configuration file generated for attend-zero-cache on 2024-12-24T23:16:06-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'attend-zero-cache'
primary_region = 'dfw'

[build]
  image = 'registry.hub.docker.com/rocicorp/zero:latest'

[env]
  LOG_LEVEL = 'debug'
  ZERO_REPLICA_FILE = '/data/sync-replica.db'
  ZERO_SCHEMA_FILE = '/zero-schema.json'

[[mounts]]
  source = 'sqlite_db'
  destination = '/data'

[http_service]
  internal_port = 4848
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[files]]
  guest_path = '/zero-schema.json'
  local_path = './src/zero/zero-schema.json'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
