name: Lint & Deploy
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
  deploy:
    needs: lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        name: Setup flyctl
      - run: flyctl deploy --remote-only --config server.fly.toml
        name: Deploy Attend Server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_SERVER_APP_TOKEN }}
      - run: flyctl deploy --remote-only --config zero-cache.fly.toml
        name: Deploy Attend Zero Cache
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_ZERO_CACHE_APP_TOKEN }}
